version: '3.7'

services:

  postgis_db:
    image: postgis/postgis
    container_name: postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_MULTIPLE_DATABASES: sequelizedb, prismadb